### ISSUE TITLE
What is signature and encryption?

### ISSUE THREAD

**Issue by fxyzbtc** [Timmy49/Hello-Git#1]

**Comment by Timmy49** [comment]
A digital signature is used for encryption. Digital signatures are used to verify that a message, document or file was sent by a know, verified person or confirm and prove that a document hasn't been tampered with. A digital signature works by firstly a hashing algorithm, where the message, document or set of characters / a string of characters are passed through a sort of messing - up stage, where your message is jumbled up and mixed around. This jumbled message is then encrypted with a private key of yours. Upon reaching your target destination, the receiver can then decrypt your message with your public key and compare your new message that is jumbled again. If the original hash that you created match with the hash that the receiver has created using your public key, then your signature is verified. 

Encryption is the process of converting a string of characters, then converted into what is know as ciphertext, the jumbled up version of your plain text using a set of algorithms and a key. Encryption is used to hide messages from other people for confidentiality. The two types of encryption include Symmetric Encryption, the simpler version with only a private key that the receiver and sender knows, and the other is the complex version, called Asymmetric Encryption. Symmetric Encryption is much simpler, whereas the sender uses the private key to encrypt a message, then the receiver uses the same key to decrypt the message. This may be faster and much more straightforward, but with great simplicity comes greater risks. If this private key is shared between anyone or hacked by anyone, the whole process, message and the whole encryption system is finished. Asymmetric encryption, however, is where it comes to play. 

Explaining asymmetric encryption takes too long. Bah.
