### ISSUE TITLE
How to ask questions in a smart way?

### ISSUE THREAD

**Issue by fxyzbtc** [Timmy49/Hello-Git#21]

**Comment by Timmy49** [comment]
1. Get straight to the point. Start with your intentions and what you want to know, including unnecessary information will just stall your question.
2. Provide relevant information. If the person you are asking your question to needs more information, make sure the info you give back is relevant and answers their question clearly and concisely. 
3. Keep your structure clear. If you have multiple small questions, don't jumble them together. Keep it to sections and ask one question at a time, if another question is sort of repeated, it shouldn't be required.
