### ISSUE TITLE
How a os is booted, eg modern linux

### ISSUE THREAD

**Issue by fxyzbtc** [Timmy49/Hello-Git#22]

**Comment by Timmy49** [comment]
When turning on a computer, the first thing that is activated is the BIOS system. It stands for basic input output system. First, it checks your HDD or SSD ( Hard Disk Drive or Solid State Drive ) integrity, and then continues to execute a boot loader program, like GRUB.

Most modern Linux operating systems boot using Grub, also known as GNU GRUB. It stands for Grand unified Bootloader and its usually the first thing you see after booting up your computer. The simple menu allows you to choose a few booting options, eg. boot a specific image you want. It automatically boots the latest kernal image by default. Then, your image takes over and starts starts the booting process for your operating system.
