### ISSUE TITLE
What does it mean when I run sudo or as administrator(in windows)?

### ISSUE THREAD

**Issue by fxyzbtc** [Timmy49/Hello-Git#23]

**Comment by Timmy49** [comment]
When running sudo or as admin in windows means that you are allowing the software or application you are running to have access to the inner files and workings of the computer. THis is extremely dangerous to do if you run suspicious applications or viruses, as, it can completely obliterate your computer and inner working. By default, if not necessary, you should simply run applications without sudo or admin privileges and if necessary, check if the application is trustable before doing so.
