### ISSUE TITLE
How can I make sure the software I installed is safe

### ISSUE THREAD

**Issue by fxyzbtc** [Timmy49/Hello-Git#24]

**Comment by Timmy49** [comment]
Simple methods include making sure you downloaded your software from a trustable source. Many websites or downloads provide certificates / digital signatures you can use to verify that the source is a confirmed developer. reading reviews and ratings can also benefit and make sure that the source is used by many people with no issues. You can also make sure that the software doesn't have permission to access anything it doesn't need to. Default anti virus softwares built in your laptop most of the time automatically detects threats or irregular files in your downloaded software. If anything seems suspicious with the sofware / applciation, completely uninstalling it is the best way, and make sure that you completely check the software details and trustability before reinstalling it.

**Comment by Timmy49** [comment]
Simple methods include making sure you downloaded your software from a trustable source. Many websites or downloads provide certificates / digital signatures you can use to verify that the source is a confirmed developer. reading reviews and ratings can also benefit and make sure that the source is used by many people with no issues. You can also make sure that the software doesn't have permission to access anything it doesn't need to. Default anti virus softwares built in your laptop most of the time automatically detects threats or irregular files in your downloaded software. If anything seems suspicious with the sofware / applciation, completely uninstalling it is the best way, and make sure that you completely check the software details and trustability before reinstalling it.
