### ISSUE TITLE
Is your home wifi trustable?

### ISSUE THREAD

**Issue by fxyzbtc** [Timmy49/Hello-Git#29]
Why? How to protect/verify your wifi is trustable?

**Comment by Timmy49** [comment]
most of the basic but trustable security is already setup by default. WPA3 / WPA2 is the most standard and trustable security option. As usual, strong passwords are also a basic security measure to protect wifi. Keeping router firmware ( the inner workings and the controllings of a router ) up to date is also makes sure that the router is updated with the latest fixes for security vunerabilities.

regularly checking the devices connected to your device can also make sure no unauthorized devices are connected to your internet. Internet traffic can also show signs of irregular / high data usage, which might indicate that someone is using your internet. Using trustworthy and popular, reputable brands is also a great way to make sure your internet is from a trusted company / source.

**Comment by Timmy49** [comment]
most of the basic but trustable security is already setup by default. WPA3 / WPA2 is the most standard and trustable security option. As usual, strong passwords are also a basic security measure to protect wifi. Keeping router firmware ( the inner workings and the controllings of a router ) up to date is also makes sure that the router is updated with the latest fixes for security vunerabilities.

regularly checking the devices connected to your device can also make sure no unauthorized devices are connected to your internet. Internet traffic can also show signs of irregular / high data usage, which might indicate that someone is using your internet. Using trustworthy and popular, reputable brands is also a great way to make sure your internet is from a trusted company / source.
