### ISSUE TITLE
What is the best business or work model to support personal finance?

### ISSUE THREAD

**Issue by fxyzbtc** [Timmy49/Hello-Git#30]
How do people do to live?

What is difference of careers or work?
Are they all respectful? Then are they all having similar pressure? Then are they having similar benefits?

Which model is better? Work for others or work for self?

**Comment by Timmy49** [comment]
1. E-Commerce
Benefits include long term passive income, and high scalability, potentially growing into global markets with higher income
Starting setup of trading and selling goods online can be difficult, requires continuous customer service and contacting etc. 

2. Investing
Potential for vast accumulation with many choices based on personal skills and preferences, eg. estate investing, stocks etc. 
Requires knowledge for successful investments and most of the time, involves risks and blindly relying on luck.

3. Real estates
while expensive on setup, in the long run, estates can be very beneficial and earning. 
requires lots of wealth during initial setup and requires ongoing management / maintenance. 

Most of these options are long term and require regular management, eg. Customer service, withdrawal / deposit ( investing ). However, long term, these options can potentially earn high amounts of money if you have the knowledge and wealth to setup. In e commerce, wealth and supplies / goods are required, in investing, the larger the amount of money deposited, the higher the income, in estates, vast amounts of money is required to setup and knowledge is required for successful management.

most of these options are to support yourself. Known as freelancing, setting up money making methods your self.

**Comment by Timmy49** [comment]
E-Commerce
Benefits include long term passive income, and high scalability, potentially growing into global markets with higher income
Starting setup of trading and selling goods online can be difficult, requires continuous customer service and contacting etc.

Investing
Potential for vast accumulation with many choices based on personal skills and preferences, eg. estate investing, stocks etc.
Requires knowledge for successful investments and most of the time, involves risks and blindly relying on luck.

Real estates
while expensive on setup, in the long run, estates can be very beneficial and earning.
requires lots of wealth during initial setup and requires ongoing management / maintenance.

Most of these options are long term and require regular management, eg. Customer service, withdrawal / deposit ( investing ). However, long term, these options can potentially earn high amounts of money if you have the knowledge and wealth to setup. In e commerce, wealth and supplies / goods are required, in investing, the larger the amount of money deposited, the higher the income, in estates, vast amounts of money is required to setup and knowledge is required for successful management.

most of these options are to support yourself. Known as freelancing, setting up money making methods your self.
