### ISSUE TITLE
Said the best business is setup-and-forgot

### ISSUE THREAD

**Issue by fxyzbtc** [Timmy49/Hello-Git#32]
Setup and forgot business is earning 24hourx7days even you are sleeping, even you are getting older, even you cannot stand.

Could you list some of these work or career or business?

Is it good? Is it difficult? Does it worth to do if it takes long time to reach, to try, to fail, to persist the direction?

**Comment by Timmy49** [comment]
1. Saving accounts. Depositing a lot of money can provide a lot of interest in long periods of time.
2. Estate managing. Owning mass amounts of estates can earn you a lot of income over periods of time whenever someone purchases one of your estates. 
3. Content creating is another method where after creating a popular video, views and revenue increase over time. 
4. Investment. A great way to earn money and setup and forget method. However, regular modifications eg. pulling out money and depositing more money would be required for maximum interest and income. 

Setup and forget business methods usually take long periods of time to gain income and usually isn't very predictable, mostly relying on the market success. Most of the time, setup and forget business methods shouldn't be main money making method, but a second, extra method for extra income. It's quite difficult to setup and maintain, but if you know how to do it, over long periods of time, it would be worth it.
