### ISSUE TITLE
How to run a company and how to get profit

### ISSUE THREAD

**Issue by fxyzbtc** [Timmy49/Hello-Git#37]

**Comment by Timmy49** [comment]
The first and most important fundamental point to clarify before starting with any company is to clearly plan out your idea on how you are going to achieve everything and what you want to achieve. Define your vision of what you want to create and hopefully that provides a clear direction or pathway of where and what your company wants to aim for. Research on your current target market / industry trends and look out for competitors. Make sure your workers share or understand your vision so they have a clear idea on what to work on. Imagine this like a video game. Keep and eye out of everything you currently have. Budgeting, resource control and steady income are key features to look out when growing your company. After successfully establishing the fundamentals of your company, most of the work would be taken over by your workers.
