### ISSUE TITLE
How does driver of taxi and truck make a living?

### ISSUE THREAD

**Issue by fxyzbtc** [Timmy49/Hello-Git#44]

**Comment by Timmy49** [comment]
Taxi or truck drivers often live and work a difficult life. Earnings are limited and often most of what you earn goes to the company you work for or used to fund the fuel for your vehicle. Taxi drivers earn money by charging customers certain amounts of money according to how far and how much time it would take to travel to their destination. Airport charges and tolls are charged to the customer and most of the time, the large amount of money the actual driver earns are from tips or a small amount of paid sum by the customer. The starting cost of buying a vehicle itself, fuel and permits are extremely expensive, especially in Singapore. Long hours in the car and uncertain income also add on to the pressure and frustration that many drivers experience in their long work hours. 

Truck drivers live similar working lives, earning money according to the amount of miles / distance per hour they carry goods from one area to another. Some drivers work under contracts of other companies for a more stable source of money. Buying a vehicle and the cost of fuel are also massive problems for truck drivers, and the long hours away from home and the physical demands of unloading cargo and focusing for a lot of time in a cramped vehicle are also extremely difficult point areas of a truck driver.
